### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by akohout** [randallb/angular-hammer#12]
Hey,

you've written in your README that one has to define the module hmTouchEvents as dependency. Your module is named hmTouchevents (with lower e). Just wanted to let you know this :-)

**Comment by paulftw** [comment]
+1
this typo causes exception "Uncaught Error: No module: hmTouchEvents"

**Comment by randallb** [comment]
I'm probably going to unpublish this module because the new `ng-touch` module is a lot better than my stuff. It's being released in 1.2.
