### ISSUE TITLE
ngTouch isn't full feature compalient as hammer.

### ISSUE THREAD

**Issue by darkyen** [randallb/angular-hammer#19]
I have seen ngTouch, and it does not looks as feature compalient as hammer, maybe continue this project ?

**Comment by randallb** [comment]
I'm just lazy. :) I don't really need it... so if anyone else wants to run with it, I'll post a message.

**Comment by darkyen** [comment]
no issues being lazy. code is liability anyways... I can fix bugs if any ... though the way you have taken it here is pretty darn robust
