### ISSUE TITLE
Triggers all hm attributes in the document

### ISSUE THREAD

**Issue by ringvold** [randallb/angular-hammer#3]
When I change the ng-click to hm-tap the first button (with the hm-tap attribute) seem to trigger the all hm-tap attributes on the page not only the one for the button being pressed and the other buttons does not trigger anything.
Is this a bug or have I done something wrong?

**Comment by randallb** [comment]
Do you have a code sample you could show? Maybe a plunker?

**Comment by ringvold** [comment]
http://plnkr.co/edit/KGNUnD

As you see the first button triggers the activity of both tap buttons and the second tap button does not work.
Same buttons under with ng-click as reference.

Edit: Oops. Accidentally closed the issue. Sorry.

**Comment by randallb** [comment]
Nope! It's my bad. This should have an isolate scope.

Fixing.

**Comment by randallb** [comment]
Forgot to do the fancy close, but it's fixed in master now.
