### ISSUE TITLE
event on parent will trigger event on ALL children

### ISSUE THREAD

**Issue by hbrls** [randallb/angular-hammer#5]
The dom is like:

```
<div id="parent" ng-controller="myApp.ctrl.Parent" hm-swipe="parentSwipe()">
    <ul id="child" ng-controller="myApp.ctrl.Children">
        <li ng-repeat="brd in boards" hm-tap="childTap(brd)">{{brd.name}}</li>
    </ul>
</div>
```

If there is no `hm-swipe` on `parent`, all works as expected.

But after I added `hm-swipe` to `parent`, if I `tap` one of the children, `tap`s of all children will be triggered.

And if its `ng-click` on `parent`, everything is OK.

You can see it here: http://jsfiddle.net/hbrls/L3TJ5/.

I'm not sure if it's an issue here or I misused `angular` and `hammer`. Could you please help me to find out?

**Comment by randallb** [comment]
Haven't had a chance to check in yet... will check tomorrow or next week.

**Comment by McKean** [comment]
Is there an update on this?
I'm experiencing the same problem... this makes it impossible to nest touch events.
