### ISSUE TITLE
hm-action disables hammerjs events on the site

### ISSUE THREAD

**Issue by MaestroJurko** [randallb/angular-hammer#9]
I have a partial view that is used in ngView and javascript under <script> tag in partial html does not work. Do you know why?
index.html
<div ng-view>

partial.html
<div hm-tap="doSomething">
  <h2 id="myId">Tap me</h2>
  <script>
      $('#myId').hammer().on("tap", function(event) {
     alert("dsadadas");
       });
</script>

**Comment by randallb** [comment]
FYI I'm killing this project when angular 1.2 comes out.
